-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ControlledBurstCheck is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    enable : IN STD_LOGIC;
    burst_length : IN STD_LOGIC_VECTOR (31 downto 0);
    burst_period : IN STD_LOGIC_VECTOR (31 downto 0);
    TDATAin_V : IN STD_LOGIC_VECTOR (31 downto 0);
    TKEEPin_V : IN STD_LOGIC_VECTOR (3 downto 0);
    TVALIDin : IN STD_LOGIC;
    TLASTin : IN STD_LOGIC;
    numerrors_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    numerrors_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ControlledBurstCheck is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ControlledBurstCheck,hls_ip_2017_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu095-ffva2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.022000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=65,HLS_SYN_LUT=1087}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_ADAB5AAC : STD_LOGIC_VECTOR (31 downto 0) := "10101101101010110101101010101100";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv24_AB5AAC : STD_LOGIC_VECTOR (23 downto 0) := "101010110101101010101100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv16_5AAC : STD_LOGIC_VECTOR (15 downto 0) := "0101101010101100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_AC : STD_LOGIC_VECTOR (7 downto 0) := "10101100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal reg_numerrors_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ref_data_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal enable_read_read_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal TVALIDin_read_read_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal TLASTin_read_read_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_1053_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_1061_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_213_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_231_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp1_fu_235_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp16_cast_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_257_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp2_fu_261_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp17_cast_fu_267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_283_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_287_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp18_cast_fu_293_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comp_V_1_fu_245_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal comp_V_4_fu_303_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp6_demorgan_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comp_V_2_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal comp_V_5_fu_323_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp13_demorgan_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal comp_V_3_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal comp_V_6_fu_349_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal comp_V_fu_375_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_383_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_415_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_427_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_439_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_451_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_463_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_475_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_487_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_499_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_511_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_535_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_547_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_559_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_571_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_583_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_595_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_607_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_619_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_631_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_643_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_655_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_667_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_679_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_703_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_fu_715_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_727_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_739_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_751_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_747_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_63_cast_fu_735_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_65_cast_fu_759_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp5_fu_769_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp4_fu_763_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp53_cast_fu_775_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_59_cast_fu_687_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_62_cast_fu_723_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp7_fu_785_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_61_cast_fu_711_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_58_cast_fu_675_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp8_fu_795_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp55_cast_fu_791_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp56_cast_fu_801_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp9_fu_805_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp6_fu_779_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp54_cast_fu_811_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_37_cast_fu_591_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_60_cast_fu_699_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp11_fu_821_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_41_cast_fu_615_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_35_cast_fu_579_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp12_fu_831_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp59_cast_fu_827_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp60_cast_fu_837_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp13_fu_841_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_45_cast_fu_639_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_39_cast_fu_603_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp14_fu_851_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_57_cast_fu_663_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_43_cast_fu_627_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp15_fu_861_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp62_cast_fu_857_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp63_cast_fu_867_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp16_fu_871_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp58_cast_fu_847_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp61_cast_fu_877_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp17_fu_881_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp10_fu_815_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp57_cast_fu_887_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_14_cast_fu_399_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_47_cast_fu_651_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp19_fu_897_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_16_cast_fu_423_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_13_cast_fu_387_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp20_fu_907_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp67_cast_fu_903_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp68_cast_fu_913_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp21_fu_917_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_18_cast_fu_447_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_15_cast_fu_411_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp22_fu_927_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_20_cast_fu_471_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_17_cast_fu_435_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp23_fu_937_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp70_cast_fu_933_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp71_cast_fu_943_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp24_fu_947_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp66_cast_fu_923_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp69_cast_fu_953_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp25_fu_957_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_22_cast_fu_495_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_19_cast_fu_459_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp26_fu_967_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_25_cast_fu_519_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_21_cast_fu_483_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp27_fu_977_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp74_cast_fu_973_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp75_cast_fu_983_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp28_fu_987_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_29_cast_fu_543_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_23_cast_fu_507_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp29_fu_997_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_31_cast_fu_555_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_33_cast_fu_567_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_27_cast_fu_531_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp30_fu_1007_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp31_fu_1013_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp77_cast_fu_1003_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp78_cast_fu_1019_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp32_fu_1023_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp73_cast_fu_993_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp76_cast_fu_1029_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp33_fu_1033_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp65_cast_fu_963_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp72_cast_fu_1039_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp34_fu_1043_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp18_fu_891_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp64_cast_fu_1049_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_58 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    reg_numerrors_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                reg_numerrors_V <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = enable_read_read_fu_146_p2) and (ap_const_lv1_1 = ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6))) then 
                    reg_numerrors_V <= ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6;
                end if; 
            end if;
        end if;
    end process;


    ref_data_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_58 = ap_const_boolean_1)) then
                if ((ap_const_lv1_1 = TLASTin_read_read_fu_134_p2)) then 
                    ref_data_V <= ap_const_lv32_0;
                elsif ((TLASTin_read_read_fu_134_p2 = ap_const_lv1_0)) then 
                    ref_data_V <= tmp_1_fu_1061_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    TLASTin_read_read_fu_134_p2 <= (0=>TLASTin, others=>'-');
    TVALIDin_read_read_fu_140_p2 <= (0=>TVALIDin, others=>'-');
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_condition_58_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_146_p2, TVALIDin_read_read_fu_140_p2)
    begin
                ap_condition_58 <= ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2));
    end process;


    ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_146_p2, TVALIDin_read_read_fu_140_p2, TLASTin_read_read_fu_134_p2)
    begin
        if (((TVALIDin_read_read_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = enable_read_read_fu_146_p2))) then 
            ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 <= ap_const_lv1_0;
        elsif ((((TLASTin_read_read_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TLASTin_read_read_fu_134_p2) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)))) then 
            ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 <= "X";
        end if; 
    end process;


    ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6_assign_proc : process(TLASTin_read_read_fu_134_p2, tmp_s_fu_1053_p2, ap_condition_58)
    begin
        if ((ap_condition_58 = ap_const_boolean_1)) then
            if ((TLASTin_read_read_fu_134_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 <= tmp_s_fu_1053_p2;
            elsif ((ap_const_lv1_1 = TLASTin_read_read_fu_134_p2)) then 
                ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 <= ap_const_lv32_0;
            else 
                ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    comp_V_1_fu_245_p2 <= (tmp16_cast_fu_241_p1 xor ref_data_V);
    comp_V_2_fu_271_p2 <= (tmp17_cast_fu_267_p1 xor ref_data_V);
    comp_V_3_fu_297_p2 <= (tmp18_cast_fu_293_p1 xor ref_data_V);
    comp_V_4_fu_303_p3 <= 
        r_V_fu_219_p2 when (tmp_2_fu_203_p2(0) = '1') else 
        ap_const_lv32_0;
    comp_V_5_fu_323_p3 <= 
        comp_V_1_fu_245_p2 when (sel_tmp2_fu_317_p2(0) = '1') else 
        comp_V_4_fu_303_p3;
    comp_V_6_fu_349_p3 <= 
        comp_V_2_fu_271_p2 when (sel_tmp7_fu_343_p2(0) = '1') else 
        comp_V_5_fu_323_p3;
    comp_V_fu_375_p3 <= 
        comp_V_3_fu_297_p2 when (sel_tmp3_fu_369_p2(0) = '1') else 
        comp_V_6_fu_349_p3;
    enable_read_read_fu_146_p2 <= (0=>enable, others=>'-');

    numerrors_V_assign_proc : process(reg_numerrors_V, ap_CS_fsm_state1, enable_read_read_fu_146_p2, TVALIDin_read_read_fu_140_p2, TLASTin_read_read_fu_134_p2, tmp_s_fu_1053_p2)
    begin
        if ((((TLASTin_read_read_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TLASTin_read_read_fu_134_p2) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)))) then 
            numerrors_V <= tmp_s_fu_1053_p2;
        elsif (((TVALIDin_read_read_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = enable_read_read_fu_146_p2))) then 
            numerrors_V <= reg_numerrors_V;
        else 
            numerrors_V <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    numerrors_V_ap_vld_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_146_p2, TVALIDin_read_read_fu_140_p2, TLASTin_read_read_fu_134_p2)
    begin
        if ((((TVALIDin_read_read_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)) or ((TLASTin_read_read_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = TLASTin_read_read_fu_134_p2) and (ap_const_lv1_1 = TVALIDin_read_read_fu_140_p2) and (ap_const_lv1_1 = enable_read_read_fu_146_p2)))) then 
            numerrors_V_ap_vld <= ap_const_logic_1;
        else 
            numerrors_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_13_cast_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_383_p1),2));
    p_Result_14_cast_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_391_p3),2));
    p_Result_15_cast_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_403_p3),2));
    p_Result_16_cast_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_415_p3),2));
    p_Result_17_cast_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_427_p3),2));
    p_Result_18_cast_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_439_p3),2));
    p_Result_19_cast_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_451_p3),2));
    p_Result_20_cast_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_463_p3),2));
    p_Result_21_cast_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_475_p3),2));
    p_Result_22_cast_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_487_p3),2));
    p_Result_23_cast_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_499_p3),2));
    p_Result_25_cast_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_511_p3),2));
    p_Result_27_cast_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_523_p3),2));
    p_Result_29_cast_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_535_p3),2));
    p_Result_31_cast_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_547_p3),2));
    p_Result_33_cast_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_559_p3),2));
    p_Result_35_cast_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_571_p3),2));
    p_Result_37_cast_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_583_p3),2));
    p_Result_39_cast_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_595_p3),2));
    p_Result_41_cast_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_607_p3),2));
    p_Result_43_cast_fu_627_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_619_p3),2));
    p_Result_45_cast_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_631_p3),2));
    p_Result_47_cast_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_643_p3),2));
    p_Result_57_cast_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_655_p3),2));
    p_Result_58_cast_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_667_p3),2));
    p_Result_59_cast_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_679_p3),2));
    p_Result_60_cast_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_691_p3),2));
    p_Result_61_cast_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_703_p3),2));
    p_Result_62_cast_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_715_p3),2));
    p_Result_63_cast_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_727_p3),2));
    p_Result_65_cast_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_40_fu_751_p3),2));
    p_Result_s_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_39_fu_739_p3),32));
    r_V_fu_219_p2 <= (tmp_fu_213_p2 xor ref_data_V);
    sel_tmp13_demorgan_fu_357_p2 <= (tmp_6_fu_251_p2 or sel_tmp6_demorgan_fu_331_p2);
    sel_tmp1_fu_311_p2 <= (tmp_2_fu_203_p2 xor ap_const_lv1_1);
    sel_tmp2_fu_317_p2 <= (tmp_3_fu_225_p2 and sel_tmp1_fu_311_p2);
    sel_tmp3_fu_369_p2 <= (tmp_9_fu_277_p2 and sel_tmp_fu_363_p2);
    sel_tmp6_demorgan_fu_331_p2 <= (tmp_3_fu_225_p2 or tmp_2_fu_203_p2);
    sel_tmp6_fu_337_p2 <= (sel_tmp6_demorgan_fu_331_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_343_p2 <= (tmp_6_fu_251_p2 and sel_tmp6_fu_337_p2);
    sel_tmp_fu_363_p2 <= (sel_tmp13_demorgan_fu_357_p2 xor ap_const_lv1_1);
    tmp10_fu_815_p2 <= std_logic_vector(unsigned(tmp6_fu_779_p2) + unsigned(tmp54_cast_fu_811_p1));
    tmp11_fu_821_p2 <= std_logic_vector(unsigned(p_Result_37_cast_fu_591_p1) + unsigned(p_Result_60_cast_fu_699_p1));
    tmp12_fu_831_p2 <= std_logic_vector(unsigned(p_Result_41_cast_fu_615_p1) + unsigned(p_Result_35_cast_fu_579_p1));
    tmp13_fu_841_p2 <= std_logic_vector(unsigned(tmp59_cast_fu_827_p1) + unsigned(tmp60_cast_fu_837_p1));
    tmp14_fu_851_p2 <= std_logic_vector(unsigned(p_Result_45_cast_fu_639_p1) + unsigned(p_Result_39_cast_fu_603_p1));
    tmp15_fu_861_p2 <= std_logic_vector(unsigned(p_Result_57_cast_fu_663_p1) + unsigned(p_Result_43_cast_fu_627_p1));
    tmp16_cast_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_235_p2),32));
    tmp16_fu_871_p2 <= std_logic_vector(unsigned(tmp62_cast_fu_857_p1) + unsigned(tmp63_cast_fu_867_p1));
    tmp17_cast_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp2_fu_261_p2),32));
    tmp17_fu_881_p2 <= std_logic_vector(unsigned(tmp58_cast_fu_847_p1) + unsigned(tmp61_cast_fu_877_p1));
    tmp18_cast_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_fu_287_p2),32));
    tmp18_fu_891_p2 <= std_logic_vector(unsigned(tmp10_fu_815_p2) + unsigned(tmp57_cast_fu_887_p1));
    tmp19_fu_897_p2 <= std_logic_vector(unsigned(p_Result_14_cast_fu_399_p1) + unsigned(p_Result_47_cast_fu_651_p1));
    tmp1_fu_235_p2 <= (tmp_4_fu_231_p1 xor ap_const_lv24_AB5AAC);
    tmp20_fu_907_p2 <= std_logic_vector(unsigned(p_Result_16_cast_fu_423_p1) + unsigned(p_Result_13_cast_fu_387_p1));
    tmp21_fu_917_p2 <= std_logic_vector(unsigned(tmp67_cast_fu_903_p1) + unsigned(tmp68_cast_fu_913_p1));
    tmp22_fu_927_p2 <= std_logic_vector(unsigned(p_Result_18_cast_fu_447_p1) + unsigned(p_Result_15_cast_fu_411_p1));
    tmp23_fu_937_p2 <= std_logic_vector(unsigned(p_Result_20_cast_fu_471_p1) + unsigned(p_Result_17_cast_fu_435_p1));
    tmp24_fu_947_p2 <= std_logic_vector(unsigned(tmp70_cast_fu_933_p1) + unsigned(tmp71_cast_fu_943_p1));
    tmp25_fu_957_p2 <= std_logic_vector(unsigned(tmp66_cast_fu_923_p1) + unsigned(tmp69_cast_fu_953_p1));
    tmp26_fu_967_p2 <= std_logic_vector(unsigned(p_Result_22_cast_fu_495_p1) + unsigned(p_Result_19_cast_fu_459_p1));
    tmp27_fu_977_p2 <= std_logic_vector(unsigned(p_Result_25_cast_fu_519_p1) + unsigned(p_Result_21_cast_fu_483_p1));
    tmp28_fu_987_p2 <= std_logic_vector(unsigned(tmp74_cast_fu_973_p1) + unsigned(tmp75_cast_fu_983_p1));
    tmp29_fu_997_p2 <= std_logic_vector(unsigned(p_Result_29_cast_fu_543_p1) + unsigned(p_Result_23_cast_fu_507_p1));
    tmp2_fu_261_p2 <= (tmp_5_fu_257_p1 xor ap_const_lv16_5AAC);
    tmp30_fu_1007_p2 <= std_logic_vector(unsigned(p_Result_31_cast_fu_555_p1) + unsigned(p_Result_33_cast_fu_567_p1));
    tmp31_fu_1013_p2 <= std_logic_vector(unsigned(p_Result_27_cast_fu_531_p1) + unsigned(tmp30_fu_1007_p2));
    tmp32_fu_1023_p2 <= std_logic_vector(unsigned(tmp77_cast_fu_1003_p1) + unsigned(tmp78_cast_fu_1019_p1));
    tmp33_fu_1033_p2 <= std_logic_vector(unsigned(tmp73_cast_fu_993_p1) + unsigned(tmp76_cast_fu_1029_p1));
    tmp34_fu_1043_p2 <= std_logic_vector(unsigned(tmp65_cast_fu_963_p1) + unsigned(tmp72_cast_fu_1039_p1));
    tmp3_fu_287_p2 <= (tmp_7_fu_283_p1 xor ap_const_lv8_AC);
    tmp4_fu_763_p2 <= std_logic_vector(unsigned(p_Result_s_fu_747_p1) + unsigned(reg_numerrors_V));
    tmp53_cast_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_769_p2),32));
    tmp54_cast_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp9_fu_805_p2),32));
    tmp55_cast_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp7_fu_785_p2),3));
    tmp56_cast_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp8_fu_795_p2),3));
    tmp57_cast_fu_887_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp17_fu_881_p2),32));
    tmp58_cast_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp13_fu_841_p2),4));
    tmp59_cast_fu_827_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp11_fu_821_p2),3));
    tmp5_fu_769_p2 <= std_logic_vector(unsigned(p_Result_63_cast_fu_735_p1) + unsigned(p_Result_65_cast_fu_759_p1));
    tmp60_cast_fu_837_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp12_fu_831_p2),3));
    tmp61_cast_fu_877_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp16_fu_871_p2),4));
    tmp62_cast_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp14_fu_851_p2),3));
    tmp63_cast_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp15_fu_861_p2),3));
    tmp64_cast_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp34_fu_1043_p2),32));
    tmp65_cast_fu_963_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp25_fu_957_p2),5));
    tmp66_cast_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp21_fu_917_p2),4));
    tmp67_cast_fu_903_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp19_fu_897_p2),3));
    tmp68_cast_fu_913_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp20_fu_907_p2),3));
    tmp69_cast_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp24_fu_947_p2),4));
    tmp6_fu_779_p2 <= std_logic_vector(unsigned(tmp4_fu_763_p2) + unsigned(tmp53_cast_fu_775_p1));
    tmp70_cast_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp22_fu_927_p2),3));
    tmp71_cast_fu_943_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp23_fu_937_p2),3));
    tmp72_cast_fu_1039_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp33_fu_1033_p2),5));
    tmp73_cast_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp28_fu_987_p2),4));
    tmp74_cast_fu_973_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp26_fu_967_p2),3));
    tmp75_cast_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp27_fu_977_p2),3));
    tmp76_cast_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp32_fu_1023_p2),4));
    tmp77_cast_fu_1003_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp29_fu_997_p2),3));
    tmp78_cast_fu_1019_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp31_fu_1013_p2),3));
    tmp7_fu_785_p2 <= std_logic_vector(unsigned(p_Result_59_cast_fu_687_p1) + unsigned(p_Result_62_cast_fu_723_p1));
    tmp8_fu_795_p2 <= std_logic_vector(unsigned(p_Result_61_cast_fu_711_p1) + unsigned(p_Result_58_cast_fu_675_p1));
    tmp9_fu_805_p2 <= std_logic_vector(unsigned(tmp55_cast_fu_791_p1) + unsigned(tmp56_cast_fu_801_p1));
    tmp_10_fu_391_p3 <= comp_V_fu_375_p3(1 downto 1);
    tmp_11_fu_403_p3 <= comp_V_fu_375_p3(2 downto 2);
    tmp_12_fu_415_p3 <= comp_V_fu_375_p3(3 downto 3);
    tmp_13_fu_427_p3 <= comp_V_fu_375_p3(4 downto 4);
    tmp_14_fu_439_p3 <= comp_V_fu_375_p3(5 downto 5);
    tmp_15_fu_451_p3 <= comp_V_fu_375_p3(6 downto 6);
    tmp_16_fu_463_p3 <= comp_V_fu_375_p3(7 downto 7);
    tmp_17_fu_475_p3 <= comp_V_fu_375_p3(8 downto 8);
    tmp_18_fu_487_p3 <= comp_V_fu_375_p3(9 downto 9);
    tmp_19_fu_499_p3 <= comp_V_fu_375_p3(10 downto 10);
    tmp_1_fu_1061_p2 <= std_logic_vector(unsigned(ref_data_V) + unsigned(ap_const_lv32_1));
    tmp_20_fu_511_p3 <= comp_V_fu_375_p3(11 downto 11);
    tmp_21_fu_523_p3 <= comp_V_fu_375_p3(12 downto 12);
    tmp_22_fu_535_p3 <= comp_V_fu_375_p3(13 downto 13);
    tmp_23_fu_547_p3 <= comp_V_fu_375_p3(14 downto 14);
    tmp_24_fu_559_p3 <= comp_V_fu_375_p3(15 downto 15);
    tmp_25_fu_571_p3 <= comp_V_fu_375_p3(16 downto 16);
    tmp_26_fu_583_p3 <= comp_V_fu_375_p3(17 downto 17);
    tmp_27_fu_595_p3 <= comp_V_fu_375_p3(18 downto 18);
    tmp_28_fu_607_p3 <= comp_V_fu_375_p3(19 downto 19);
    tmp_29_fu_619_p3 <= comp_V_fu_375_p3(20 downto 20);
    tmp_2_fu_203_p2 <= "1" when (TKEEPin_V = ap_const_lv4_F) else "0";
    tmp_30_fu_631_p3 <= comp_V_fu_375_p3(21 downto 21);
    tmp_31_fu_643_p3 <= comp_V_fu_375_p3(22 downto 22);
    tmp_32_fu_655_p3 <= comp_V_fu_375_p3(23 downto 23);
    tmp_33_fu_667_p3 <= comp_V_fu_375_p3(24 downto 24);
    tmp_34_fu_679_p3 <= comp_V_fu_375_p3(25 downto 25);
    tmp_35_fu_691_p3 <= comp_V_fu_375_p3(26 downto 26);
    tmp_36_fu_703_p3 <= comp_V_fu_375_p3(27 downto 27);
    tmp_37_fu_715_p3 <= comp_V_fu_375_p3(28 downto 28);
    tmp_38_fu_727_p3 <= comp_V_fu_375_p3(29 downto 29);
    tmp_39_fu_739_p3 <= comp_V_fu_375_p3(30 downto 30);
    tmp_3_fu_225_p2 <= "1" when (TKEEPin_V = ap_const_lv4_7) else "0";
    tmp_40_fu_751_p3 <= comp_V_fu_375_p3(31 downto 31);
    tmp_4_fu_231_p1 <= TDATAin_V(24 - 1 downto 0);
    tmp_5_fu_257_p1 <= TDATAin_V(16 - 1 downto 0);
    tmp_6_fu_251_p2 <= "1" when (TKEEPin_V = ap_const_lv4_3) else "0";
    tmp_7_fu_283_p1 <= TDATAin_V(8 - 1 downto 0);
    tmp_8_fu_383_p1 <= comp_V_fu_375_p3(1 - 1 downto 0);
    tmp_9_fu_277_p2 <= "1" when (TKEEPin_V = ap_const_lv4_1) else "0";
    tmp_fu_213_p2 <= (TDATAin_V xor ap_const_lv32_ADAB5AAC);
    tmp_s_fu_1053_p2 <= std_logic_vector(unsigned(tmp18_fu_891_p2) + unsigned(tmp64_cast_fu_1049_p1));
end behav;
