:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2017.3
:: Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado/2017.3/../../Vivado/2017.3/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu095-ffva2104-2-e ../xilinx_com_hls_SOP_CDR_Control_1_0.zip
