-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ControlledBurstGen is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    enable : IN STD_LOGIC;
    preamble_length : IN STD_LOGIC_VECTOR (31 downto 0);
    add_delimiter : IN STD_LOGIC;
    preamble : IN STD_LOGIC_VECTOR (31 downto 0);
    delimiter : IN STD_LOGIC_VECTOR (31 downto 0);
    burst_length : IN STD_LOGIC_VECTOR (31 downto 0);
    burst_period : IN STD_LOGIC_VECTOR (31 downto 0);
    dataOut_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dataOut_TVALID : OUT STD_LOGIC;
    dataOut_TREADY : IN STD_LOGIC;
    dataOut_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataOut_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataOut_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    dataOut_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dataOut_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    dataOut_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    axis_dataOut_TVALID : OUT STD_LOGIC;
    axis_dataOut_TVALID_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ControlledBurstGen is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ControlledBurstGen,hls_ip_2017_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu095-ffva2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.721000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=67,HLS_SYN_LUT=489}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_ADAB5AAC : STD_LOGIC_VECTOR (31 downto 0) := "10101101101010110101101010101100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal data_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal init_data : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal dataOut_TDATA_blk_n : STD_LOGIC;
    signal enable_read_read_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal demorgan_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_ioackin_dataOut_TREADY : STD_LOGIC;
    signal ap_predicate_op36_write_state1 : BOOLEAN;
    signal ap_predicate_op47_write_state1 : BOOLEAN;
    signal ap_predicate_op55_write_state1 : BOOLEAN;
    signal ap_predicate_op67_write_state1 : BOOLEAN;
    signal ap_predicate_op71_write_state1 : BOOLEAN;
    signal ap_predicate_op75_write_state1 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal tmp_9_fu_257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_164_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack : STD_LOGIC := '0';
    signal grp_fu_175_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_ioackin_dataOut_TREADY : STD_LOGIC := '0';
    signal tmp_fu_185_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_not_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal demorgan_fu_251_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_113 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack <= ap_const_logic_0;
            else
                if (((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)))) then 
                    ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack <= ap_const_logic_0;
                elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_start = ap_const_logic_1) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)))) then 
                    ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_dataOut_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_dataOut_TREADY <= ap_const_logic_0;
            else
                if (((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op71_write_state1)))) then 
                    ap_reg_ioackin_dataOut_TREADY <= ap_const_logic_0;
                elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op71_write_state1)))) then 
                    ap_reg_ioackin_dataOut_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    data_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                data_count <= ap_const_lv32_0;
            else
                if ((ap_condition_113 = ap_const_boolean_1)) then
                    if (((ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1))) then 
                        data_count <= tmp_9_fu_257_p2;
                    elsif ((ap_const_boolean_1 = ap_predicate_op36_write_state1)) then 
                        data_count <= ap_const_lv32_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    init_data_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                init_data <= ap_const_lv32_0;
            else
                if (((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_lv1_0 = tmp_5_fu_227_p2) and (tmp_3_fu_221_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (ap_const_lv1_1 = tmp_8_fu_233_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    init_data <= grp_fu_164_p2;
                elsif ((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1))) then 
                    init_data <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_io_assign_proc : process(ap_sig_ioackin_dataOut_TREADY, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op67_write_state1, ap_predicate_op71_write_state1, ap_predicate_op75_write_state1)
    begin
                ap_block_state1_io <= (((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or ((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)) or ((ap_const_logic_0 = ap_sig_ioackin_dataOut_TREADY) and (ap_const_boolean_1 = ap_predicate_op71_write_state1)));
    end process;


    ap_condition_113_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
                ap_condition_113 <= (not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op36_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2)
    begin
                ap_predicate_op36_write_state1 <= ((tmp_1_fu_191_p2 = ap_const_lv1_0) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op47_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_5_fu_227_p2)
    begin
                ap_predicate_op47_write_state1 <= ((ap_const_lv1_0 = tmp_5_fu_227_p2) and (tmp_3_fu_221_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op55_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_5_fu_227_p2)
    begin
                ap_predicate_op55_write_state1 <= ((tmp_3_fu_221_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_5_fu_227_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op67_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2, demorgan_fu_251_p2)
    begin
                ap_predicate_op67_write_state1 <= ((ap_const_lv1_0 = demorgan_fu_251_p2) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op71_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2, demorgan_fu_251_p2)
    begin
                ap_predicate_op71_write_state1 <= ((tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = demorgan_fu_251_p2) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op75_write_state1_assign_proc : process(enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2)
    begin
                ap_predicate_op75_write_state1 <= ((ap_const_lv1_1 = tmp_4_fu_239_p2) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_ioackin_dataOut_TREADY_assign_proc : process(dataOut_TREADY, ap_reg_ioackin_dataOut_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY)) then 
            ap_sig_ioackin_dataOut_TREADY <= dataOut_TREADY;
        else 
            ap_sig_ioackin_dataOut_TREADY <= ap_const_logic_1;
        end if; 
    end process;


    axis_dataOut_TVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op75_write_state1)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_start = ap_const_logic_1) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)))) then 
            axis_dataOut_TVALID <= ap_const_logic_1;
        elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)))) then 
            axis_dataOut_TVALID <= ap_const_logic_0;
        else 
            axis_dataOut_TVALID <= 'X';
        end if; 
    end process;


    axis_dataOut_TVALID_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op75_write_state1, ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_start = ap_const_logic_1) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_0 = ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_axis_dataOut_TVALID_dummy_ack) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)))) then 
            axis_dataOut_TVALID_ap_vld <= ap_const_logic_1;
        else 
            axis_dataOut_TVALID_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    dataOut_TDATA_assign_proc : process(ap_start, ap_CS_fsm_state1, preamble, delimiter, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op67_write_state1, ap_predicate_op71_write_state1, ap_predicate_op75_write_state1, grp_fu_175_p2)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1))) then 
            dataOut_TDATA <= preamble;
        elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op71_write_state1))) then 
            dataOut_TDATA <= delimiter;
        elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)))) then 
            dataOut_TDATA <= grp_fu_175_p2;
        elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)))) then 
            dataOut_TDATA <= ap_const_lv32_0;
        else 
            dataOut_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dataOut_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, dataOut_TREADY, enable_read_read_fu_114_p2, tmp_1_fu_191_p2, tmp_3_fu_221_p2, tmp_4_fu_239_p2, demorgan_fu_251_p2, tmp_5_fu_227_p2)
    begin
        if ((((tmp_1_fu_191_p2 = ap_const_lv1_0) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = tmp_5_fu_227_p2) and (tmp_3_fu_221_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_3_fu_221_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_5_fu_227_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_0 = demorgan_fu_251_p2) and (tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_4_fu_239_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = demorgan_fu_251_p2) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_1 = tmp_4_fu_239_p2) and (ap_const_lv1_1 = tmp_3_fu_221_p2) and (ap_const_lv1_1 = tmp_1_fu_191_p2) and (enable_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dataOut_TDATA_blk_n <= dataOut_TREADY;
        else 
            dataOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dataOut_TDEST <= ap_const_lv6_0;
    dataOut_TID <= ap_const_lv5_0;
    dataOut_TKEEP <= ap_const_lv4_F;

    dataOut_TLAST_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op67_write_state1, ap_predicate_op71_write_state1, ap_predicate_op75_write_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1))) then 
            dataOut_TLAST <= ap_const_lv1_1;
        elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op71_write_state1)))) then 
            dataOut_TLAST <= ap_const_lv1_0;
        else 
            dataOut_TLAST <= "X";
        end if; 
    end process;

    dataOut_TSTRB <= ap_const_lv4_0;
    dataOut_TUSER <= ap_const_lv2_0;

    dataOut_TVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_predicate_op36_write_state1, ap_predicate_op47_write_state1, ap_predicate_op55_write_state1, ap_predicate_op67_write_state1, ap_predicate_op71_write_state1, ap_predicate_op75_write_state1, ap_reg_ioackin_dataOut_TREADY)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op67_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op55_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op47_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op36_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op75_write_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_0 = ap_reg_ioackin_dataOut_TREADY) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_1 = ap_predicate_op71_write_state1)))) then 
            dataOut_TVALID <= ap_const_logic_1;
        else 
            dataOut_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    demorgan_fu_251_p1 <= (0=>add_delimiter, others=>'-');
    demorgan_fu_251_p2 <= (p_not_fu_245_p2 and demorgan_fu_251_p1);
    enable_read_read_fu_114_p2 <= (0=>enable, others=>'-');
    grp_fu_164_p2 <= std_logic_vector(unsigned(init_data) + unsigned(ap_const_lv32_1));
    grp_fu_175_p2 <= (init_data xor ap_const_lv32_ADAB5AAC);
    p_not_fu_245_p2 <= "1" when (data_count = preamble_length) else "0";
    tmp_1_fu_191_p2 <= "1" when (unsigned(data_count) < unsigned(tmp_fu_185_p2)) else "0";
    tmp_2_fu_215_p2 <= std_logic_vector(unsigned(burst_length) + unsigned(ap_const_lv32_FFFFFFFF));
    tmp_3_fu_221_p2 <= "1" when (unsigned(data_count) < unsigned(tmp_2_fu_215_p2)) else "0";
    tmp_4_fu_239_p2 <= "1" when (unsigned(data_count) < unsigned(preamble_length)) else "0";
    tmp_5_fu_227_p2 <= "1" when (data_count = tmp_2_fu_215_p2) else "0";
    tmp_8_fu_233_p2 <= "1" when (data_count = burst_length) else "0";
    tmp_9_fu_257_p2 <= std_logic_vector(unsigned(data_count) + unsigned(ap_const_lv32_1));
    tmp_fu_185_p2 <= std_logic_vector(unsigned(burst_period) + unsigned(ap_const_lv32_FFFFFFFF));
end behav;
