-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SOPDetect is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    enable : IN STD_LOGIC;
    TDATAin_V : IN STD_LOGIC_VECTOR (31 downto 0);
    Thresholdin_V : IN STD_LOGIC_VECTOR (7 downto 0);
    SOP_detected : OUT STD_LOGIC;
    SOP_detected_ap_vld : OUT STD_LOGIC;
    Packet_detected : OUT STD_LOGIC;
    Packet_detected_ap_vld : OUT STD_LOGIC );
end;


architecture behav of SOPDetect is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "SOPDetect,hls_ip_2017_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu095-ffva2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.723250,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6,HLS_SYN_LUT=521}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv9_1FD : STD_LOGIC_VECTOR (8 downto 0) := "111111101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal SOP_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal NumConsequtiveNoData : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_phi_mux_storemerge_phi_fu_154_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal enable_read_read_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal SOP_reg_load_1_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal SOP_reg_new_1_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal SOP_reg_flag_1_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal NumConsequtiveNoData_2_fu_972_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal NumConsequtiveNoData_1_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_s_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_166_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_186_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_246_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_258_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_270_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_282_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_294_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_318_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_330_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_342_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_366_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_378_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_390_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_402_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_414_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_438_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_450_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_462_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_474_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_486_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_510_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_522_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_cast_fu_530_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_cast_fu_518_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_546_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_27_cast_fu_494_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_28_cast_fu_506_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp1_fu_556_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp34_cast_fu_552_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp35_cast_fu_562_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp2_fu_566_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_cast_fu_446_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_cast_fu_458_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp3_fu_576_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_cast_fu_470_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_26_cast_fu_482_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp4_fu_586_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp37_cast_fu_582_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp38_cast_fu_592_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp5_fu_596_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp33_cast_fu_572_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp36_cast_fu_602_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp6_fu_606_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_cast_fu_350_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_cast_fu_362_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp7_fu_616_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_cast_fu_374_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_cast_fu_386_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp8_fu_626_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp41_cast_fu_622_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp42_cast_fu_632_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp9_fu_636_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_19_cast_fu_398_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_cast_fu_410_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp10_fu_646_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_cast_fu_422_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_cast_fu_434_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp11_fu_656_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp44_cast_fu_652_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp45_cast_fu_662_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp12_fu_666_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp40_cast_fu_642_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp43_cast_fu_672_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp13_fu_676_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp32_cast_fu_612_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp39_cast_fu_682_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp14_fu_686_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_cast_fu_194_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_cast_fu_170_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp15_fu_696_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_cast_fu_218_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_cast_fu_182_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp16_fu_706_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp49_cast_fu_702_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp50_cast_fu_712_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp17_fu_716_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_cast_fu_242_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_cast_fu_206_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp18_fu_726_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_cast_fu_266_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_cast_fu_230_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp19_fu_736_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp52_cast_fu_732_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp53_cast_fu_742_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp20_fu_746_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp48_cast_fu_722_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp51_cast_fu_752_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp21_fu_756_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_10_cast_fu_290_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_cast_fu_254_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp22_fu_766_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_cast_fu_314_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_cast_fu_278_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp23_fu_776_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp56_cast_fu_772_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp57_cast_fu_782_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp24_fu_786_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_cast_fu_338_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_cast_fu_302_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp25_fu_796_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_cast_fu_542_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_cast_fu_326_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp26_fu_806_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp59_cast_fu_802_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp60_cast_fu_812_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp27_fu_816_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp55_cast_fu_792_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp58_cast_fu_822_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp28_fu_826_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp47_cast_fu_762_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp54_cast_fu_832_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp29_fu_836_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp31_cast_fu_692_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp46_cast_fu_842_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal reg_numones_V_fu_846_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal reg_numones_V_cast_fu_852_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_demorgan_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_s_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_897_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_SOP_reg_flag_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal SOP_reg_load_7_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_cast_fu_934_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_65_cast_fu_944_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_fu_938_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_2_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    NumConsequtiveNoData_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                NumConsequtiveNoData <= ap_const_lv4_0;
            else
                if (((ap_const_lv1_1 = NumConsequtiveNoData_1_fu_966_p2) and (enable_read_read_fu_130_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    NumConsequtiveNoData <= NumConsequtiveNoData_2_fu_972_p3;
                end if; 
            end if;
        end if;
    end process;


    SOP_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                SOP_reg <= ap_const_lv1_0;
            else
                if (((ap_const_lv1_1 = SOP_reg_flag_1_fu_915_p2) and (enable_read_read_fu_130_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    SOP_reg <= SOP_reg_new_1_fu_921_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    NumConsequtiveNoData_1_fu_966_p2 <= (tmp_1_fu_887_p2 or not_tmp_2_fu_960_p2);
    NumConsequtiveNoData_2_fu_972_p3 <= 
        tmp_2_fu_897_p2 when (tmp_4_fu_948_p2(0) = '1') else 
        ap_const_lv4_0;
    Packet_detected <= ap_phi_mux_storemerge_phi_fu_154_p4(0);

    Packet_detected_ap_vld_assign_proc : process(ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            Packet_detected_ap_vld <= ap_const_logic_1;
        else 
            Packet_detected_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    SOP_detected_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_130_p2, p_not_s_fu_868_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((enable_read_read_fu_130_p2 = ap_const_lv1_1)) then 
                SOP_detected <= p_not_s_fu_868_p2(0);
            elsif ((ap_const_lv1_0 = enable_read_read_fu_130_p2)) then 
                SOP_detected <= ap_const_logic_0;
            else 
                SOP_detected <= 'X';
            end if;
        else 
            SOP_detected <= 'X';
        end if; 
    end process;


    SOP_detected_ap_vld_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_130_p2)
    begin
        if ((((enable_read_read_fu_130_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_0 = enable_read_read_fu_130_p2)))) then 
            SOP_detected_ap_vld <= ap_const_logic_1;
        else 
            SOP_detected_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    SOP_reg_flag_1_fu_915_p2 <= (p_SOP_reg_flag_fu_909_p2 or not_tmp_s_fu_875_p2);
    SOP_reg_load_1_fu_927_p2 <= (SOP_reg_new_1_fu_921_p2 and SOP_reg_load_7_fu_881_p2);
    SOP_reg_load_7_fu_881_p2 <= (not_tmp_s_fu_875_p2 or SOP_reg);
    SOP_reg_new_1_fu_921_p2 <= (p_SOP_reg_flag_fu_909_p2 xor ap_const_lv1_1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_phi_mux_storemerge_phi_fu_154_p4_assign_proc : process(ap_CS_fsm_state1, enable_read_read_fu_130_p2, SOP_reg_load_1_fu_927_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((enable_read_read_fu_130_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_154_p4 <= SOP_reg_load_1_fu_927_p2;
            elsif ((ap_const_lv1_0 = enable_read_read_fu_130_p2)) then 
                ap_phi_mux_storemerge_phi_fu_154_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_storemerge_phi_fu_154_p4 <= "X";
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_154_p4 <= "X";
        end if; 
    end process;

    enable_read_read_fu_130_p2 <= (0=>enable, others=>'-');
    lhs_V_cast_fu_934_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Thresholdin_V),9));
    not_tmp_2_fu_960_p2 <= (tmp_4_fu_948_p2 xor ap_const_lv1_1);
    not_tmp_s_fu_875_p2 <= (tmp_s_fu_856_p2 xor ap_const_lv1_1);
    p_SOP_reg_flag_fu_909_p2 <= (tmp_3_fu_903_p2 and tmp_1_fu_887_p2);
    p_not_demorgan_fu_862_p2 <= (tmp_s_fu_856_p2 or SOP_reg);
    p_not_s_fu_868_p2 <= (p_not_demorgan_fu_862_p2 xor ap_const_lv1_1);
    r_V_fu_938_p2 <= std_logic_vector(signed(ap_const_lv9_1FD) + signed(lhs_V_cast_fu_934_p1));
    reg_numones_V_cast_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_numones_V_fu_846_p2),8));
    reg_numones_V_fu_846_p2 <= std_logic_vector(unsigned(tmp31_cast_fu_692_p1) + unsigned(tmp46_cast_fu_842_p1));
    tmp10_fu_646_p2 <= std_logic_vector(unsigned(tmp_19_cast_fu_398_p1) + unsigned(tmp_20_cast_fu_410_p1));
    tmp11_fu_656_p2 <= std_logic_vector(unsigned(tmp_21_cast_fu_422_p1) + unsigned(tmp_22_cast_fu_434_p1));
    tmp12_fu_666_p2 <= std_logic_vector(unsigned(tmp44_cast_fu_652_p1) + unsigned(tmp45_cast_fu_662_p1));
    tmp13_fu_676_p2 <= std_logic_vector(unsigned(tmp40_cast_fu_642_p1) + unsigned(tmp43_cast_fu_672_p1));
    tmp14_fu_686_p2 <= std_logic_vector(unsigned(tmp32_cast_fu_612_p1) + unsigned(tmp39_cast_fu_682_p1));
    tmp15_fu_696_p2 <= std_logic_vector(unsigned(tmp_2_cast_fu_194_p1) + unsigned(tmp_cast_fu_170_p1));
    tmp16_fu_706_p2 <= std_logic_vector(unsigned(tmp_4_cast_fu_218_p1) + unsigned(tmp_1_cast_fu_182_p1));
    tmp17_fu_716_p2 <= std_logic_vector(unsigned(tmp49_cast_fu_702_p1) + unsigned(tmp50_cast_fu_712_p1));
    tmp18_fu_726_p2 <= std_logic_vector(unsigned(tmp_6_cast_fu_242_p1) + unsigned(tmp_3_cast_fu_206_p1));
    tmp19_fu_736_p2 <= std_logic_vector(unsigned(tmp_8_cast_fu_266_p1) + unsigned(tmp_5_cast_fu_230_p1));
    tmp1_fu_556_p2 <= std_logic_vector(unsigned(tmp_27_cast_fu_494_p1) + unsigned(tmp_28_cast_fu_506_p1));
    tmp20_fu_746_p2 <= std_logic_vector(unsigned(tmp52_cast_fu_732_p1) + unsigned(tmp53_cast_fu_742_p1));
    tmp21_fu_756_p2 <= std_logic_vector(unsigned(tmp48_cast_fu_722_p1) + unsigned(tmp51_cast_fu_752_p1));
    tmp22_fu_766_p2 <= std_logic_vector(unsigned(tmp_10_cast_fu_290_p1) + unsigned(tmp_7_cast_fu_254_p1));
    tmp23_fu_776_p2 <= std_logic_vector(unsigned(tmp_12_cast_fu_314_p1) + unsigned(tmp_9_cast_fu_278_p1));
    tmp24_fu_786_p2 <= std_logic_vector(unsigned(tmp56_cast_fu_772_p1) + unsigned(tmp57_cast_fu_782_p1));
    tmp25_fu_796_p2 <= std_logic_vector(unsigned(tmp_14_cast_fu_338_p1) + unsigned(tmp_11_cast_fu_302_p1));
    tmp26_fu_806_p2 <= std_logic_vector(unsigned(tmp_31_cast_fu_542_p1) + unsigned(tmp_13_cast_fu_326_p1));
    tmp27_fu_816_p2 <= std_logic_vector(unsigned(tmp59_cast_fu_802_p1) + unsigned(tmp60_cast_fu_812_p1));
    tmp28_fu_826_p2 <= std_logic_vector(unsigned(tmp55_cast_fu_792_p1) + unsigned(tmp58_cast_fu_822_p1));
    tmp29_fu_836_p2 <= std_logic_vector(unsigned(tmp47_cast_fu_762_p1) + unsigned(tmp54_cast_fu_832_p1));
    tmp2_fu_566_p2 <= std_logic_vector(unsigned(tmp34_cast_fu_552_p1) + unsigned(tmp35_cast_fu_562_p1));
    tmp31_cast_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp14_fu_686_p2),6));
    tmp32_cast_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp6_fu_606_p2),5));
    tmp33_cast_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp2_fu_566_p2),4));
    tmp34_cast_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_546_p2),3));
    tmp35_cast_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_556_p2),3));
    tmp36_cast_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_596_p2),4));
    tmp37_cast_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_fu_576_p2),3));
    tmp38_cast_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_586_p2),3));
    tmp39_cast_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp13_fu_676_p2),5));
    tmp3_fu_576_p2 <= std_logic_vector(unsigned(tmp_23_cast_fu_446_p1) + unsigned(tmp_24_cast_fu_458_p1));
    tmp40_cast_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp9_fu_636_p2),4));
    tmp41_cast_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp7_fu_616_p2),3));
    tmp42_cast_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp8_fu_626_p2),3));
    tmp43_cast_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp12_fu_666_p2),4));
    tmp44_cast_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp10_fu_646_p2),3));
    tmp45_cast_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp11_fu_656_p2),3));
    tmp46_cast_fu_842_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp29_fu_836_p2),6));
    tmp47_cast_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp21_fu_756_p2),5));
    tmp48_cast_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp17_fu_716_p2),4));
    tmp49_cast_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp15_fu_696_p2),3));
    tmp4_fu_586_p2 <= std_logic_vector(unsigned(tmp_25_cast_fu_470_p1) + unsigned(tmp_26_cast_fu_482_p1));
    tmp50_cast_fu_712_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp16_fu_706_p2),3));
    tmp51_cast_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp20_fu_746_p2),4));
    tmp52_cast_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp18_fu_726_p2),3));
    tmp53_cast_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp19_fu_736_p2),3));
    tmp54_cast_fu_832_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp28_fu_826_p2),5));
    tmp55_cast_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp24_fu_786_p2),4));
    tmp56_cast_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp22_fu_766_p2),3));
    tmp57_cast_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp23_fu_776_p2),3));
    tmp58_cast_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp27_fu_816_p2),4));
    tmp59_cast_fu_802_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp25_fu_796_p2),3));
    tmp5_fu_596_p2 <= std_logic_vector(unsigned(tmp37_cast_fu_582_p1) + unsigned(tmp38_cast_fu_592_p1));
    tmp60_cast_fu_812_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp26_fu_806_p2),3));
    tmp6_fu_606_p2 <= std_logic_vector(unsigned(tmp33_cast_fu_572_p1) + unsigned(tmp36_cast_fu_602_p1));
    tmp7_fu_616_p2 <= std_logic_vector(unsigned(tmp_15_cast_fu_350_p1) + unsigned(tmp_16_cast_fu_362_p1));
    tmp8_fu_626_p2 <= std_logic_vector(unsigned(tmp_17_cast_fu_374_p1) + unsigned(tmp_18_cast_fu_386_p1));
    tmp9_fu_636_p2 <= std_logic_vector(unsigned(tmp41_cast_fu_622_p1) + unsigned(tmp42_cast_fu_632_p1));
    tmp_10_cast_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_282_p3),2));
    tmp_10_fu_222_p3 <= TDATAin_V(5 downto 5);
    tmp_11_cast_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_294_p3),2));
    tmp_11_fu_234_p3 <= TDATAin_V(6 downto 6);
    tmp_12_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_306_p3),2));
    tmp_12_fu_246_p3 <= TDATAin_V(7 downto 7);
    tmp_13_cast_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_318_p3),2));
    tmp_13_fu_258_p3 <= TDATAin_V(8 downto 8);
    tmp_14_cast_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_330_p3),2));
    tmp_14_fu_270_p3 <= TDATAin_V(9 downto 9);
    tmp_15_cast_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_342_p3),2));
    tmp_15_fu_282_p3 <= TDATAin_V(10 downto 10);
    tmp_16_cast_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_354_p3),2));
    tmp_16_fu_294_p3 <= TDATAin_V(11 downto 11);
    tmp_17_cast_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_366_p3),2));
    tmp_17_fu_306_p3 <= TDATAin_V(12 downto 12);
    tmp_18_cast_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_378_p3),2));
    tmp_18_fu_318_p3 <= TDATAin_V(13 downto 13);
    tmp_19_cast_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_390_p3),2));
    tmp_19_fu_330_p3 <= TDATAin_V(14 downto 14);
    tmp_1_cast_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_174_p3),2));
    tmp_1_fu_887_p2 <= "1" when (reg_numones_V_fu_846_p2 = ap_const_lv6_0) else "0";
    tmp_20_cast_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_402_p3),2));
    tmp_20_fu_342_p3 <= TDATAin_V(15 downto 15);
    tmp_21_cast_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_414_p3),2));
    tmp_21_fu_354_p3 <= TDATAin_V(16 downto 16);
    tmp_22_cast_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_426_p3),2));
    tmp_22_fu_366_p3 <= TDATAin_V(17 downto 17);
    tmp_23_cast_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_438_p3),2));
    tmp_23_fu_378_p3 <= TDATAin_V(18 downto 18);
    tmp_24_cast_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_450_p3),2));
    tmp_24_fu_390_p3 <= TDATAin_V(19 downto 19);
    tmp_25_cast_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_462_p3),2));
    tmp_25_fu_402_p3 <= TDATAin_V(20 downto 20);
    tmp_26_cast_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_474_p3),2));
    tmp_26_fu_414_p3 <= TDATAin_V(21 downto 21);
    tmp_27_cast_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_486_p3),2));
    tmp_27_fu_426_p3 <= TDATAin_V(22 downto 22);
    tmp_28_cast_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_498_p3),2));
    tmp_28_fu_438_p3 <= TDATAin_V(23 downto 23);
    tmp_29_cast_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_510_p3),2));
    tmp_29_fu_450_p3 <= TDATAin_V(24 downto 24);
    tmp_2_cast_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_186_p3),2));
    tmp_2_fu_897_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(NumConsequtiveNoData));
    tmp_30_cast_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_522_p3),2));
    tmp_30_fu_462_p3 <= TDATAin_V(25 downto 25);
    tmp_31_cast_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_534_p3),2));
    tmp_31_fu_474_p3 <= TDATAin_V(26 downto 26);
    tmp_32_fu_486_p3 <= TDATAin_V(27 downto 27);
    tmp_33_fu_498_p3 <= TDATAin_V(28 downto 28);
    tmp_34_fu_510_p3 <= TDATAin_V(29 downto 29);
    tmp_35_fu_522_p3 <= TDATAin_V(30 downto 30);
    tmp_36_fu_534_p3 <= TDATAin_V(31 downto 31);
    tmp_3_cast_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_198_p3),2));
    tmp_3_fu_903_p2 <= "1" when (unsigned(tmp_2_fu_897_p2) > unsigned(ap_const_lv4_9)) else "0";
    tmp_4_cast_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_210_p3),2));
    tmp_4_fu_948_p2 <= "1" when (signed(tmp_65_cast_fu_944_p1) < signed(r_V_fu_938_p2)) else "0";
    tmp_5_cast_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_222_p3),2));
    tmp_5_fu_166_p1 <= TDATAin_V(1 - 1 downto 0);
    tmp_65_cast_fu_944_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_numones_V_fu_846_p2),9));
    tmp_6_cast_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_234_p3),2));
    tmp_6_fu_174_p3 <= TDATAin_V(1 downto 1);
    tmp_7_cast_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_246_p3),2));
    tmp_7_fu_186_p3 <= TDATAin_V(2 downto 2);
    tmp_8_cast_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_258_p3),2));
    tmp_8_fu_198_p3 <= TDATAin_V(3 downto 3);
    tmp_9_cast_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_270_p3),2));
    tmp_9_fu_210_p3 <= TDATAin_V(4 downto 4);
    tmp_cast_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_166_p1),2));
    tmp_fu_546_p2 <= std_logic_vector(unsigned(tmp_30_cast_fu_530_p1) + unsigned(tmp_29_cast_fu_518_p1));
    tmp_s_fu_856_p2 <= "1" when (unsigned(reg_numones_V_cast_fu_852_p1) < unsigned(Thresholdin_V)) else "0";
end behav;
