set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[7]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TLAST]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[14]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TLAST]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TVALID]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TUSER]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[21]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TUSER]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TVALID]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TREADY]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[21]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_emulator_inst/eth_axis_usrtx_TLAST]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[7]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_emulator_inst/eth_axis_usrtx_TREADY]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_emulator_inst/eth_axis_usrtx_TUSER]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[23]}]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_emulator_inst/eth_axis_usrtx_TVALID]
set_property MARK_DEBUG true [get_nets GTH_eth_10G_emulator_inst/eth_axis_usrrx_TVALID]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[2]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[24]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list GTH_eth_10G_emulator_inst/eth_10G_FMC_gthbnk230_q2_inst/i_eth_10G_gtbnk230_q2_core_support/i_eth_10G_gtbnk230_q2_gt_wrapper_0/i_eth_10G_gtbnk230_q2_core_gtwiz_userclk_rx_inst/gtwiz_userclk_rx_usrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[0]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[1]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[2]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[3]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[4]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[5]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[6]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[7]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[8]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[9]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[10]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[11]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[12]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[13]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[14]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[15]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[16]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[17]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[18]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[19]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[20]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[21]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[22]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[23]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[24]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[25]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[26]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[27]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[28]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[29]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[30]} {GTH_eth_10G_emulator_inst/eth_axis_usrrx_TDATA[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/xxv_ethernet_0_top_inst/i_xxv_ethernet_0_core_support/i_xxv_ethernet_0_gt_wrapper_0/i_xxv_ethernet_0_core_gtwiz_userclk_rx_inst/gtwiz_userclk_rx_usrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[0]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[1]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[2]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TKEEP[3]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list GTH_eth_10G_emulator_inst/eth_10G_FMC_gthbnk230_q2_inst/i_eth_10G_gtbnk230_q2_core_support/i_eth_10G_gtbnk230_q2_gt_wrapper_0/i_eth_10G_gtbnk230_q2_core_gtwiz_userclk_tx_inst/gtwiz_userclk_tx_usrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 32 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[0]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[1]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[2]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[3]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[4]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[5]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[6]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[7]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[8]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[9]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[10]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[11]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[12]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[13]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[14]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[15]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[16]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[17]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[18]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[19]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[20]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[21]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[22]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[23]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[24]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[25]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[26]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[27]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[28]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[29]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[30]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TDATA[31]}]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/xxv_ethernet_0_top_inst/i_xxv_ethernet_0_core_support/i_xxv_ethernet_0_gt_wrapper_0/i_xxv_ethernet_0_core_gtwiz_userclk_tx_inst/gtwiz_userclk_tx_usrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 32 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[0]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[1]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[2]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[3]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[4]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[5]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[6]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[7]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[8]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[9]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[10]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[11]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[12]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[13]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[14]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[15]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[16]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[17]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[18]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[19]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[20]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[21]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[22]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[23]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[24]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[25]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[26]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[27]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[28]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[29]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[30]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list GTH_eth_10G_emulator_inst/eth_axis_usrrx_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[0]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[1]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[2]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[3]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[4]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[5]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[6]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[7]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[8]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[9]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[10]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[11]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[12]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[13]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[14]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[15]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[16]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[17]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[18]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[19]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[20]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[21]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[22]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[23]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[24]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[25]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[26]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[27]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[28]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[29]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[30]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TUSER]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrrx_TVALID]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 4 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[0]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[1]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[2]} {GTH_eth_10G_emulator_inst/eth_axis_usrtx_TKEEP[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list GTH_eth_10G_emulator_inst/eth_axis_usrtx_TLAST]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list GTH_eth_10G_emulator_inst/eth_axis_usrtx_TREADY]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list GTH_eth_10G_emulator_inst/eth_axis_usrtx_TUSER]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list GTH_eth_10G_emulator_inst/eth_axis_usrtx_TVALID]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property port_width 4 [get_debug_ports u_ila_3/probe1]
connect_debug_port u_ila_3/probe1 [get_nets [list {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[0]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[1]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[2]} {GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TKEEP[3]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
set_property port_width 1 [get_debug_ports u_ila_3/probe2]
connect_debug_port u_ila_3/probe2 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TLAST]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
set_property port_width 1 [get_debug_ports u_ila_3/probe3]
connect_debug_port u_ila_3/probe3 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TREADY]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe4]
set_property port_width 1 [get_debug_ports u_ila_3/probe4]
connect_debug_port u_ila_3/probe4 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TUSER]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe5]
set_property port_width 1 [get_debug_ports u_ila_3/probe5]
connect_debug_port u_ila_3/probe5 [get_nets [list GTH_eth_10G_to_XG_PON_if_inst/eth_axis_usrtx_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets rx_core_clk_0]
