#*****************************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# create_project_new.tcl: Tcl script for re-creating project '10G_eth_FMC_GTH'
#
# Generated by Vivado on Wed Mar 25 02:29:03 +0000 2020
# IP Build 2016188 on Wed Oct  4 21:52:56 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project_new.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/xxv_ethernet_0_gt_0/xxv_ethernet_0_gt_0.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/xxv_ethernet_0/xxv_ethernet_0.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/eth_10G_gtbnk230_q2_gt_0/eth_10G_gtbnk230_q2_gt_0.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/eth_10G_gtbnk230_q2/eth_10G_gtbnk230_q2.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/vio_top/vio_top.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/Burst_Mode_Synchronizer.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/GTH_eth_10G_emulator.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/GTH_eth_10G_to_XG_PON.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/PRBS_Generator.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/add_XG_PON_header.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/axis_ms_slv_loopback.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_clocking_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_common_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_core_support.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_exdes.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_gt_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_pkt_gen_mon.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_reset_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_sharedlogic_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_trans_debug.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_ultrascale_rx_userclk.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/eth_10G_gtbnk230_q2_ultrascale_tx_userclk.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/reset_sync.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/vio_top_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xg_PON_frame_sync.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_core_support.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_exdes.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_gt_wrapper.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_pkt_gen_mon.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_trans_debug.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_ultrascale_rx_userclk.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/xxv_ethernet_0_ultrascale_tx_userclk.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/pon_sources/top.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/variableDelay/variableDelay.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/axis_master_slave_lb_fifo/axis_master_slave_lb_fifo.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/ip_sources/ControlledBurstGen_0/ControlledBurstGen_0.xci"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/constraints/GTH_eth_10G_to_XG_PON_if.xdc"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/constraints/ila_Debug.xdc"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/sim_sources/FMC_GTH_10G_top_tb.v"
#    "E:/WorkingDir/eth_10g_axi_lb_FMC_GTH/sources/sim_sources/top_tb_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set project_name "10G_eth_FMC_GTH"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set project_name $::user_project_name
}

variable script_file
set script_file "create_project_new.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set project_name [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../projects/10G_eth_FMC_GTH"]"

# Create project
create_project ${project_name} ../projects/${project_name} -part xcvu095-ffva2104-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vcu108:part0:1.3" -objects $obj
set_property -name "corecontainer.enable" -value "1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${project_name}.cache/ip" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../sources/ip_sources/user-ip_repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../sources/ip_sources/xxv_ethernet_0_gt_0/xxv_ethernet_0_gt_0.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/xxv_ethernet_0/xxv_ethernet_0.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/eth_10G_gtbnk230_q2_gt_0/eth_10G_gtbnk230_q2_gt_0.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/eth_10G_gtbnk230_q2/eth_10G_gtbnk230_q2.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/vio_top/vio_top.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/axis_master_slave_lb_fifo/axis_master_slave_lb_fifo.xci"]"\
 "[file normalize "$origin_dir/../sources/ip_sources/variableDelay/variableDelay.xci"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/Burst_Mode_Synchronizer.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/GTH_eth_10G_emulator.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/GTH_eth_10G_to_XG_PON.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/PRBS_Generator.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/add_XG_PON_header.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/axis_ms_slv_loopback.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_clocking_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_common_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_core_support.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_exdes.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_gt_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_pkt_gen_mon.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_reset_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_sharedlogic_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_trans_debug.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_ultrascale_rx_userclk.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/eth_10G_gtbnk230_q2_ultrascale_tx_userclk.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/reset_sync.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/vio_top_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xg_PON_frame_sync.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_core_support.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_exdes.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_gt_wrapper.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_pkt_gen_mon.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_trans_debug.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_ultrascale_rx_userclk.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/xxv_ethernet_0_ultrascale_tx_userclk.v"]"\
 "[file normalize "$origin_dir/../sources/pon_sources/top.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../sources/ip_sources/xxv_ethernet_0_gt_0/xxv_ethernet_0_gt_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "$origin_dir/../sources/ip_sources/eth_10G_gtbnk230_q2_gt_0/eth_10G_gtbnk230_q2_gt_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None


# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../sources/ip_sources/user-ip_repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../sources/ip_sources/ControlledBurstGen_0/ControlledBurstGen_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None
# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top" -objects $obj

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constraints/GTH_eth_10G_to_XG_PON_if.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constraints/GTH_eth_10G_to_XG_PON_if.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constraints/ila_Debug.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constraints/ila_Debug.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/../constraints/ila_Debug.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../sources/sim_sources/FMC_GTH_10G_top_tb.v"]"\
 "[file normalize "$origin_dir/../sources/sim_sources/top_tb_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "top_tb" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xcvu095-ffva2104-2-e -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property -name "report_strategy" -value "Vivado Synthesis Default Reports" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.flatten_hierarchy" -value "none" -objects $obj

set reports [get_report_configs -of_objects $obj]
if { [llength $reports ] > 0 } {
  delete_report_config [get_report_configs -of_objects $obj]
}
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xcvu095-ffva2104-2-e -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "report_strategy" -value "Vivado Implementation Default Reports" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

set reports [get_report_configs -of_objects $obj]
if { [llength $reports ] > 0 } {
  delete_report_config [get_report_configs -of_objects $obj]
}
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:$project_name"
