// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ControlledBurstCheck,hls_ip_2017_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu095-ffva2104-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.022000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=65,HLS_SYN_LUT=1087}" *)

module ControlledBurstCheck (
        ap_clk,
        ap_rst,
        enable,
        burst_length,
        burst_period,
        TDATAin_V,
        TKEEPin_V,
        TVALIDin,
        TLASTin,
        numerrors_V,
        numerrors_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   enable;
input  [31:0] burst_length;
input  [31:0] burst_period;
input  [31:0] TDATAin_V;
input  [3:0] TKEEPin_V;
input   TVALIDin;
input   TLASTin;
output  [31:0] numerrors_V;
output   numerrors_V_ap_vld;

reg[31:0] numerrors_V;
reg numerrors_V_ap_vld;

reg   [31:0] reg_numerrors_V;
reg   [31:0] ref_data_V;
reg   [0:0] ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] enable_read_read_fu_146_p2;
wire   [0:0] TVALIDin_read_read_fu_140_p2;
wire   [0:0] TLASTin_read_read_fu_134_p2;
reg   [31:0] ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6;
wire   [31:0] tmp_s_fu_1053_p2;
wire   [31:0] tmp_1_fu_1061_p2;
wire   [31:0] tmp_fu_213_p2;
wire   [23:0] tmp_4_fu_231_p1;
wire   [23:0] tmp1_fu_235_p2;
wire   [31:0] tmp16_cast_fu_241_p1;
wire   [15:0] tmp_5_fu_257_p1;
wire   [15:0] tmp2_fu_261_p2;
wire   [31:0] tmp17_cast_fu_267_p1;
wire   [7:0] tmp_7_fu_283_p1;
wire   [7:0] tmp3_fu_287_p2;
wire   [31:0] tmp18_cast_fu_293_p1;
wire   [0:0] tmp_2_fu_203_p2;
wire   [31:0] r_V_fu_219_p2;
wire   [0:0] tmp_3_fu_225_p2;
wire   [0:0] sel_tmp1_fu_311_p2;
wire   [0:0] sel_tmp2_fu_317_p2;
wire   [31:0] comp_V_1_fu_245_p2;
wire   [31:0] comp_V_4_fu_303_p3;
wire   [0:0] sel_tmp6_demorgan_fu_331_p2;
wire   [0:0] tmp_6_fu_251_p2;
wire   [0:0] sel_tmp6_fu_337_p2;
wire   [0:0] sel_tmp7_fu_343_p2;
wire   [31:0] comp_V_2_fu_271_p2;
wire   [31:0] comp_V_5_fu_323_p3;
wire   [0:0] sel_tmp13_demorgan_fu_357_p2;
wire   [0:0] tmp_9_fu_277_p2;
wire   [0:0] sel_tmp_fu_363_p2;
wire   [0:0] sel_tmp3_fu_369_p2;
wire   [31:0] comp_V_3_fu_297_p2;
wire   [31:0] comp_V_6_fu_349_p3;
wire   [31:0] comp_V_fu_375_p3;
wire   [0:0] tmp_8_fu_383_p1;
wire   [0:0] tmp_10_fu_391_p3;
wire   [0:0] tmp_11_fu_403_p3;
wire   [0:0] tmp_12_fu_415_p3;
wire   [0:0] tmp_13_fu_427_p3;
wire   [0:0] tmp_14_fu_439_p3;
wire   [0:0] tmp_15_fu_451_p3;
wire   [0:0] tmp_16_fu_463_p3;
wire   [0:0] tmp_17_fu_475_p3;
wire   [0:0] tmp_18_fu_487_p3;
wire   [0:0] tmp_19_fu_499_p3;
wire   [0:0] tmp_20_fu_511_p3;
wire   [0:0] tmp_21_fu_523_p3;
wire   [0:0] tmp_22_fu_535_p3;
wire   [0:0] tmp_23_fu_547_p3;
wire   [0:0] tmp_24_fu_559_p3;
wire   [0:0] tmp_25_fu_571_p3;
wire   [0:0] tmp_26_fu_583_p3;
wire   [0:0] tmp_27_fu_595_p3;
wire   [0:0] tmp_28_fu_607_p3;
wire   [0:0] tmp_29_fu_619_p3;
wire   [0:0] tmp_30_fu_631_p3;
wire   [0:0] tmp_31_fu_643_p3;
wire   [0:0] tmp_32_fu_655_p3;
wire   [0:0] tmp_33_fu_667_p3;
wire   [0:0] tmp_34_fu_679_p3;
wire   [0:0] tmp_35_fu_691_p3;
wire   [0:0] tmp_36_fu_703_p3;
wire   [0:0] tmp_37_fu_715_p3;
wire   [0:0] tmp_38_fu_727_p3;
wire   [0:0] tmp_39_fu_739_p3;
wire   [0:0] tmp_40_fu_751_p3;
wire   [31:0] p_Result_s_fu_747_p1;
wire   [1:0] p_Result_63_cast_fu_735_p1;
wire   [1:0] p_Result_65_cast_fu_759_p1;
wire   [1:0] tmp5_fu_769_p2;
wire   [31:0] tmp4_fu_763_p2;
wire   [31:0] tmp53_cast_fu_775_p1;
wire   [1:0] p_Result_59_cast_fu_687_p1;
wire   [1:0] p_Result_62_cast_fu_723_p1;
wire   [1:0] tmp7_fu_785_p2;
wire   [1:0] p_Result_61_cast_fu_711_p1;
wire   [1:0] p_Result_58_cast_fu_675_p1;
wire   [1:0] tmp8_fu_795_p2;
wire   [2:0] tmp55_cast_fu_791_p1;
wire   [2:0] tmp56_cast_fu_801_p1;
wire   [2:0] tmp9_fu_805_p2;
wire   [31:0] tmp6_fu_779_p2;
wire   [31:0] tmp54_cast_fu_811_p1;
wire   [1:0] p_Result_37_cast_fu_591_p1;
wire   [1:0] p_Result_60_cast_fu_699_p1;
wire   [1:0] tmp11_fu_821_p2;
wire   [1:0] p_Result_41_cast_fu_615_p1;
wire   [1:0] p_Result_35_cast_fu_579_p1;
wire   [1:0] tmp12_fu_831_p2;
wire   [2:0] tmp59_cast_fu_827_p1;
wire   [2:0] tmp60_cast_fu_837_p1;
wire   [2:0] tmp13_fu_841_p2;
wire   [1:0] p_Result_45_cast_fu_639_p1;
wire   [1:0] p_Result_39_cast_fu_603_p1;
wire   [1:0] tmp14_fu_851_p2;
wire   [1:0] p_Result_57_cast_fu_663_p1;
wire   [1:0] p_Result_43_cast_fu_627_p1;
wire   [1:0] tmp15_fu_861_p2;
wire   [2:0] tmp62_cast_fu_857_p1;
wire   [2:0] tmp63_cast_fu_867_p1;
wire   [2:0] tmp16_fu_871_p2;
wire   [3:0] tmp58_cast_fu_847_p1;
wire   [3:0] tmp61_cast_fu_877_p1;
wire   [3:0] tmp17_fu_881_p2;
wire   [31:0] tmp10_fu_815_p2;
wire   [31:0] tmp57_cast_fu_887_p1;
wire   [1:0] p_Result_14_cast_fu_399_p1;
wire   [1:0] p_Result_47_cast_fu_651_p1;
wire   [1:0] tmp19_fu_897_p2;
wire   [1:0] p_Result_16_cast_fu_423_p1;
wire   [1:0] p_Result_13_cast_fu_387_p1;
wire   [1:0] tmp20_fu_907_p2;
wire   [2:0] tmp67_cast_fu_903_p1;
wire   [2:0] tmp68_cast_fu_913_p1;
wire   [2:0] tmp21_fu_917_p2;
wire   [1:0] p_Result_18_cast_fu_447_p1;
wire   [1:0] p_Result_15_cast_fu_411_p1;
wire   [1:0] tmp22_fu_927_p2;
wire   [1:0] p_Result_20_cast_fu_471_p1;
wire   [1:0] p_Result_17_cast_fu_435_p1;
wire   [1:0] tmp23_fu_937_p2;
wire   [2:0] tmp70_cast_fu_933_p1;
wire   [2:0] tmp71_cast_fu_943_p1;
wire   [2:0] tmp24_fu_947_p2;
wire   [3:0] tmp66_cast_fu_923_p1;
wire   [3:0] tmp69_cast_fu_953_p1;
wire   [3:0] tmp25_fu_957_p2;
wire   [1:0] p_Result_22_cast_fu_495_p1;
wire   [1:0] p_Result_19_cast_fu_459_p1;
wire   [1:0] tmp26_fu_967_p2;
wire   [1:0] p_Result_25_cast_fu_519_p1;
wire   [1:0] p_Result_21_cast_fu_483_p1;
wire   [1:0] tmp27_fu_977_p2;
wire   [2:0] tmp74_cast_fu_973_p1;
wire   [2:0] tmp75_cast_fu_983_p1;
wire   [2:0] tmp28_fu_987_p2;
wire   [1:0] p_Result_29_cast_fu_543_p1;
wire   [1:0] p_Result_23_cast_fu_507_p1;
wire   [1:0] tmp29_fu_997_p2;
wire   [1:0] p_Result_31_cast_fu_555_p1;
wire   [1:0] p_Result_33_cast_fu_567_p1;
wire   [1:0] p_Result_27_cast_fu_531_p1;
wire   [1:0] tmp30_fu_1007_p2;
wire   [1:0] tmp31_fu_1013_p2;
wire   [2:0] tmp77_cast_fu_1003_p1;
wire   [2:0] tmp78_cast_fu_1019_p1;
wire   [2:0] tmp32_fu_1023_p2;
wire   [3:0] tmp73_cast_fu_993_p1;
wire   [3:0] tmp76_cast_fu_1029_p1;
wire   [3:0] tmp33_fu_1033_p2;
wire   [4:0] tmp65_cast_fu_963_p1;
wire   [4:0] tmp72_cast_fu_1039_p1;
wire   [4:0] tmp34_fu_1043_p2;
wire   [31:0] tmp18_fu_891_p2;
wire   [31:0] tmp64_cast_fu_1049_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_condition_58;

// power-on initialization
initial begin
#0 reg_numerrors_V = 32'd0;
#0 ref_data_V = 32'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_numerrors_V <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'd1 == enable_read_read_fu_146_p2) & (1'd1 == ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6))) begin
            reg_numerrors_V <= ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_58 == 1'b1)) begin
        if ((1'd1 == TLASTin_read_read_fu_134_p2)) begin
            ref_data_V <= 32'd0;
        end else if ((TLASTin_read_read_fu_134_p2 == 1'd0)) begin
            ref_data_V <= tmp_1_fu_1061_p2;
        end
    end
end

always @ (*) begin
    if (((TVALIDin_read_read_fu_140_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == enable_read_read_fu_146_p2))) begin
        ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 = 1'd0;
    end else if ((((TLASTin_read_read_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)) | ((1'b1 == ap_CS_fsm_state1) & (1'd1 == TLASTin_read_read_fu_134_p2) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)))) begin
        ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 = 1'd1;
    end else begin
        ap_phi_mux_reg_numerrors_V_flag_phi_fu_174_p6 = 'bx;
    end
end

always @ (*) begin
    if ((ap_condition_58 == 1'b1)) begin
        if ((TLASTin_read_read_fu_134_p2 == 1'd0)) begin
            ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 = tmp_s_fu_1053_p2;
        end else if ((1'd1 == TLASTin_read_read_fu_134_p2)) begin
            ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 = 32'd0;
        end else begin
            ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 = 'bx;
        end
    end else begin
        ap_phi_mux_reg_numerrors_V_new_phi_fu_188_p6 = 'bx;
    end
end

always @ (*) begin
    if ((((TLASTin_read_read_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)) | ((1'b1 == ap_CS_fsm_state1) & (1'd1 == TLASTin_read_read_fu_134_p2) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)))) begin
        numerrors_V = tmp_s_fu_1053_p2;
    end else if (((TVALIDin_read_read_fu_140_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == enable_read_read_fu_146_p2))) begin
        numerrors_V = reg_numerrors_V;
    end else begin
        numerrors_V = 'bx;
    end
end

always @ (*) begin
    if ((((TVALIDin_read_read_fu_140_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == enable_read_read_fu_146_p2)) | ((TLASTin_read_read_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)) | ((1'b1 == ap_CS_fsm_state1) & (1'd1 == TLASTin_read_read_fu_134_p2) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2)))) begin
        numerrors_V_ap_vld = 1'b1;
    end else begin
        numerrors_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TLASTin_read_read_fu_134_p2 = TLASTin;

assign TVALIDin_read_read_fu_140_p2 = TVALIDin;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_58 = ((1'b1 == ap_CS_fsm_state1) & (1'd1 == TVALIDin_read_read_fu_140_p2) & (1'd1 == enable_read_read_fu_146_p2));
end

assign comp_V_1_fu_245_p2 = (tmp16_cast_fu_241_p1 ^ ref_data_V);

assign comp_V_2_fu_271_p2 = (tmp17_cast_fu_267_p1 ^ ref_data_V);

assign comp_V_3_fu_297_p2 = (tmp18_cast_fu_293_p1 ^ ref_data_V);

assign comp_V_4_fu_303_p3 = ((tmp_2_fu_203_p2[0:0] === 1'b1) ? r_V_fu_219_p2 : 32'd0);

assign comp_V_5_fu_323_p3 = ((sel_tmp2_fu_317_p2[0:0] === 1'b1) ? comp_V_1_fu_245_p2 : comp_V_4_fu_303_p3);

assign comp_V_6_fu_349_p3 = ((sel_tmp7_fu_343_p2[0:0] === 1'b1) ? comp_V_2_fu_271_p2 : comp_V_5_fu_323_p3);

assign comp_V_fu_375_p3 = ((sel_tmp3_fu_369_p2[0:0] === 1'b1) ? comp_V_3_fu_297_p2 : comp_V_6_fu_349_p3);

assign enable_read_read_fu_146_p2 = enable;

assign p_Result_13_cast_fu_387_p1 = tmp_8_fu_383_p1;

assign p_Result_14_cast_fu_399_p1 = tmp_10_fu_391_p3;

assign p_Result_15_cast_fu_411_p1 = tmp_11_fu_403_p3;

assign p_Result_16_cast_fu_423_p1 = tmp_12_fu_415_p3;

assign p_Result_17_cast_fu_435_p1 = tmp_13_fu_427_p3;

assign p_Result_18_cast_fu_447_p1 = tmp_14_fu_439_p3;

assign p_Result_19_cast_fu_459_p1 = tmp_15_fu_451_p3;

assign p_Result_20_cast_fu_471_p1 = tmp_16_fu_463_p3;

assign p_Result_21_cast_fu_483_p1 = tmp_17_fu_475_p3;

assign p_Result_22_cast_fu_495_p1 = tmp_18_fu_487_p3;

assign p_Result_23_cast_fu_507_p1 = tmp_19_fu_499_p3;

assign p_Result_25_cast_fu_519_p1 = tmp_20_fu_511_p3;

assign p_Result_27_cast_fu_531_p1 = tmp_21_fu_523_p3;

assign p_Result_29_cast_fu_543_p1 = tmp_22_fu_535_p3;

assign p_Result_31_cast_fu_555_p1 = tmp_23_fu_547_p3;

assign p_Result_33_cast_fu_567_p1 = tmp_24_fu_559_p3;

assign p_Result_35_cast_fu_579_p1 = tmp_25_fu_571_p3;

assign p_Result_37_cast_fu_591_p1 = tmp_26_fu_583_p3;

assign p_Result_39_cast_fu_603_p1 = tmp_27_fu_595_p3;

assign p_Result_41_cast_fu_615_p1 = tmp_28_fu_607_p3;

assign p_Result_43_cast_fu_627_p1 = tmp_29_fu_619_p3;

assign p_Result_45_cast_fu_639_p1 = tmp_30_fu_631_p3;

assign p_Result_47_cast_fu_651_p1 = tmp_31_fu_643_p3;

assign p_Result_57_cast_fu_663_p1 = tmp_32_fu_655_p3;

assign p_Result_58_cast_fu_675_p1 = tmp_33_fu_667_p3;

assign p_Result_59_cast_fu_687_p1 = tmp_34_fu_679_p3;

assign p_Result_60_cast_fu_699_p1 = tmp_35_fu_691_p3;

assign p_Result_61_cast_fu_711_p1 = tmp_36_fu_703_p3;

assign p_Result_62_cast_fu_723_p1 = tmp_37_fu_715_p3;

assign p_Result_63_cast_fu_735_p1 = tmp_38_fu_727_p3;

assign p_Result_65_cast_fu_759_p1 = tmp_40_fu_751_p3;

assign p_Result_s_fu_747_p1 = tmp_39_fu_739_p3;

assign r_V_fu_219_p2 = (tmp_fu_213_p2 ^ ref_data_V);

assign sel_tmp13_demorgan_fu_357_p2 = (tmp_6_fu_251_p2 | sel_tmp6_demorgan_fu_331_p2);

assign sel_tmp1_fu_311_p2 = (tmp_2_fu_203_p2 ^ 1'd1);

assign sel_tmp2_fu_317_p2 = (tmp_3_fu_225_p2 & sel_tmp1_fu_311_p2);

assign sel_tmp3_fu_369_p2 = (tmp_9_fu_277_p2 & sel_tmp_fu_363_p2);

assign sel_tmp6_demorgan_fu_331_p2 = (tmp_3_fu_225_p2 | tmp_2_fu_203_p2);

assign sel_tmp6_fu_337_p2 = (sel_tmp6_demorgan_fu_331_p2 ^ 1'd1);

assign sel_tmp7_fu_343_p2 = (tmp_6_fu_251_p2 & sel_tmp6_fu_337_p2);

assign sel_tmp_fu_363_p2 = (sel_tmp13_demorgan_fu_357_p2 ^ 1'd1);

assign tmp10_fu_815_p2 = (tmp6_fu_779_p2 + tmp54_cast_fu_811_p1);

assign tmp11_fu_821_p2 = (p_Result_37_cast_fu_591_p1 + p_Result_60_cast_fu_699_p1);

assign tmp12_fu_831_p2 = (p_Result_41_cast_fu_615_p1 + p_Result_35_cast_fu_579_p1);

assign tmp13_fu_841_p2 = (tmp59_cast_fu_827_p1 + tmp60_cast_fu_837_p1);

assign tmp14_fu_851_p2 = (p_Result_45_cast_fu_639_p1 + p_Result_39_cast_fu_603_p1);

assign tmp15_fu_861_p2 = (p_Result_57_cast_fu_663_p1 + p_Result_43_cast_fu_627_p1);

assign tmp16_cast_fu_241_p1 = tmp1_fu_235_p2;

assign tmp16_fu_871_p2 = (tmp62_cast_fu_857_p1 + tmp63_cast_fu_867_p1);

assign tmp17_cast_fu_267_p1 = tmp2_fu_261_p2;

assign tmp17_fu_881_p2 = (tmp58_cast_fu_847_p1 + tmp61_cast_fu_877_p1);

assign tmp18_cast_fu_293_p1 = tmp3_fu_287_p2;

assign tmp18_fu_891_p2 = (tmp10_fu_815_p2 + tmp57_cast_fu_887_p1);

assign tmp19_fu_897_p2 = (p_Result_14_cast_fu_399_p1 + p_Result_47_cast_fu_651_p1);

assign tmp1_fu_235_p2 = (tmp_4_fu_231_p1 ^ 24'd11229868);

assign tmp20_fu_907_p2 = (p_Result_16_cast_fu_423_p1 + p_Result_13_cast_fu_387_p1);

assign tmp21_fu_917_p2 = (tmp67_cast_fu_903_p1 + tmp68_cast_fu_913_p1);

assign tmp22_fu_927_p2 = (p_Result_18_cast_fu_447_p1 + p_Result_15_cast_fu_411_p1);

assign tmp23_fu_937_p2 = (p_Result_20_cast_fu_471_p1 + p_Result_17_cast_fu_435_p1);

assign tmp24_fu_947_p2 = (tmp70_cast_fu_933_p1 + tmp71_cast_fu_943_p1);

assign tmp25_fu_957_p2 = (tmp66_cast_fu_923_p1 + tmp69_cast_fu_953_p1);

assign tmp26_fu_967_p2 = (p_Result_22_cast_fu_495_p1 + p_Result_19_cast_fu_459_p1);

assign tmp27_fu_977_p2 = (p_Result_25_cast_fu_519_p1 + p_Result_21_cast_fu_483_p1);

assign tmp28_fu_987_p2 = (tmp74_cast_fu_973_p1 + tmp75_cast_fu_983_p1);

assign tmp29_fu_997_p2 = (p_Result_29_cast_fu_543_p1 + p_Result_23_cast_fu_507_p1);

assign tmp2_fu_261_p2 = (tmp_5_fu_257_p1 ^ 16'd23212);

assign tmp30_fu_1007_p2 = (p_Result_31_cast_fu_555_p1 + p_Result_33_cast_fu_567_p1);

assign tmp31_fu_1013_p2 = (p_Result_27_cast_fu_531_p1 + tmp30_fu_1007_p2);

assign tmp32_fu_1023_p2 = (tmp77_cast_fu_1003_p1 + tmp78_cast_fu_1019_p1);

assign tmp33_fu_1033_p2 = (tmp73_cast_fu_993_p1 + tmp76_cast_fu_1029_p1);

assign tmp34_fu_1043_p2 = (tmp65_cast_fu_963_p1 + tmp72_cast_fu_1039_p1);

assign tmp3_fu_287_p2 = (tmp_7_fu_283_p1 ^ 8'd172);

assign tmp4_fu_763_p2 = (p_Result_s_fu_747_p1 + reg_numerrors_V);

assign tmp53_cast_fu_775_p1 = tmp5_fu_769_p2;

assign tmp54_cast_fu_811_p1 = tmp9_fu_805_p2;

assign tmp55_cast_fu_791_p1 = tmp7_fu_785_p2;

assign tmp56_cast_fu_801_p1 = tmp8_fu_795_p2;

assign tmp57_cast_fu_887_p1 = tmp17_fu_881_p2;

assign tmp58_cast_fu_847_p1 = tmp13_fu_841_p2;

assign tmp59_cast_fu_827_p1 = tmp11_fu_821_p2;

assign tmp5_fu_769_p2 = (p_Result_63_cast_fu_735_p1 + p_Result_65_cast_fu_759_p1);

assign tmp60_cast_fu_837_p1 = tmp12_fu_831_p2;

assign tmp61_cast_fu_877_p1 = tmp16_fu_871_p2;

assign tmp62_cast_fu_857_p1 = tmp14_fu_851_p2;

assign tmp63_cast_fu_867_p1 = tmp15_fu_861_p2;

assign tmp64_cast_fu_1049_p1 = tmp34_fu_1043_p2;

assign tmp65_cast_fu_963_p1 = tmp25_fu_957_p2;

assign tmp66_cast_fu_923_p1 = tmp21_fu_917_p2;

assign tmp67_cast_fu_903_p1 = tmp19_fu_897_p2;

assign tmp68_cast_fu_913_p1 = tmp20_fu_907_p2;

assign tmp69_cast_fu_953_p1 = tmp24_fu_947_p2;

assign tmp6_fu_779_p2 = (tmp4_fu_763_p2 + tmp53_cast_fu_775_p1);

assign tmp70_cast_fu_933_p1 = tmp22_fu_927_p2;

assign tmp71_cast_fu_943_p1 = tmp23_fu_937_p2;

assign tmp72_cast_fu_1039_p1 = tmp33_fu_1033_p2;

assign tmp73_cast_fu_993_p1 = tmp28_fu_987_p2;

assign tmp74_cast_fu_973_p1 = tmp26_fu_967_p2;

assign tmp75_cast_fu_983_p1 = tmp27_fu_977_p2;

assign tmp76_cast_fu_1029_p1 = tmp32_fu_1023_p2;

assign tmp77_cast_fu_1003_p1 = tmp29_fu_997_p2;

assign tmp78_cast_fu_1019_p1 = tmp31_fu_1013_p2;

assign tmp7_fu_785_p2 = (p_Result_59_cast_fu_687_p1 + p_Result_62_cast_fu_723_p1);

assign tmp8_fu_795_p2 = (p_Result_61_cast_fu_711_p1 + p_Result_58_cast_fu_675_p1);

assign tmp9_fu_805_p2 = (tmp55_cast_fu_791_p1 + tmp56_cast_fu_801_p1);

assign tmp_10_fu_391_p3 = comp_V_fu_375_p3[32'd1];

assign tmp_11_fu_403_p3 = comp_V_fu_375_p3[32'd2];

assign tmp_12_fu_415_p3 = comp_V_fu_375_p3[32'd3];

assign tmp_13_fu_427_p3 = comp_V_fu_375_p3[32'd4];

assign tmp_14_fu_439_p3 = comp_V_fu_375_p3[32'd5];

assign tmp_15_fu_451_p3 = comp_V_fu_375_p3[32'd6];

assign tmp_16_fu_463_p3 = comp_V_fu_375_p3[32'd7];

assign tmp_17_fu_475_p3 = comp_V_fu_375_p3[32'd8];

assign tmp_18_fu_487_p3 = comp_V_fu_375_p3[32'd9];

assign tmp_19_fu_499_p3 = comp_V_fu_375_p3[32'd10];

assign tmp_1_fu_1061_p2 = (ref_data_V + 32'd1);

assign tmp_20_fu_511_p3 = comp_V_fu_375_p3[32'd11];

assign tmp_21_fu_523_p3 = comp_V_fu_375_p3[32'd12];

assign tmp_22_fu_535_p3 = comp_V_fu_375_p3[32'd13];

assign tmp_23_fu_547_p3 = comp_V_fu_375_p3[32'd14];

assign tmp_24_fu_559_p3 = comp_V_fu_375_p3[32'd15];

assign tmp_25_fu_571_p3 = comp_V_fu_375_p3[32'd16];

assign tmp_26_fu_583_p3 = comp_V_fu_375_p3[32'd17];

assign tmp_27_fu_595_p3 = comp_V_fu_375_p3[32'd18];

assign tmp_28_fu_607_p3 = comp_V_fu_375_p3[32'd19];

assign tmp_29_fu_619_p3 = comp_V_fu_375_p3[32'd20];

assign tmp_2_fu_203_p2 = ((TKEEPin_V == 4'd15) ? 1'b1 : 1'b0);

assign tmp_30_fu_631_p3 = comp_V_fu_375_p3[32'd21];

assign tmp_31_fu_643_p3 = comp_V_fu_375_p3[32'd22];

assign tmp_32_fu_655_p3 = comp_V_fu_375_p3[32'd23];

assign tmp_33_fu_667_p3 = comp_V_fu_375_p3[32'd24];

assign tmp_34_fu_679_p3 = comp_V_fu_375_p3[32'd25];

assign tmp_35_fu_691_p3 = comp_V_fu_375_p3[32'd26];

assign tmp_36_fu_703_p3 = comp_V_fu_375_p3[32'd27];

assign tmp_37_fu_715_p3 = comp_V_fu_375_p3[32'd28];

assign tmp_38_fu_727_p3 = comp_V_fu_375_p3[32'd29];

assign tmp_39_fu_739_p3 = comp_V_fu_375_p3[32'd30];

assign tmp_3_fu_225_p2 = ((TKEEPin_V == 4'd7) ? 1'b1 : 1'b0);

assign tmp_40_fu_751_p3 = comp_V_fu_375_p3[32'd31];

assign tmp_4_fu_231_p1 = TDATAin_V[23:0];

assign tmp_5_fu_257_p1 = TDATAin_V[15:0];

assign tmp_6_fu_251_p2 = ((TKEEPin_V == 4'd3) ? 1'b1 : 1'b0);

assign tmp_7_fu_283_p1 = TDATAin_V[7:0];

assign tmp_8_fu_383_p1 = comp_V_fu_375_p3[0:0];

assign tmp_9_fu_277_p2 = ((TKEEPin_V == 4'd1) ? 1'b1 : 1'b0);

assign tmp_fu_213_p2 = (TDATAin_V ^ 32'd2913688236);

assign tmp_s_fu_1053_p2 = (tmp18_fu_891_p2 + tmp64_cast_fu_1049_p1);

endmodule //ControlledBurstCheck
